### ISSUE TITLE
Slower animation

### ISSUE THREAD

**Issue by timbledum** [44O/gaota#2]
Heya!

Love the game, and you should totally add to the pyxel user samples [here](https://github.com/kitao/pyxel/wiki#user-samples)!

One suggested tweak – to make the animation a bit slower, try changing lines 324 to 327 to this:

```python
        elif self.is_laddering:
            u = self.laddering[(self.y // 4) % 2]
        else:
            u = self.walk[(self.x // 4) % 2]```

**Comment by 44O** [comment]
Hi @timbledum ,
I really appreciate your suggestion! I liked it.
Thanks.
